### ISSUE TITLE
SQL Database

### ISSUE THREAD

**Issue by Bedja** [dkhansemand/MySocialNetwork#1]
```
Fejl
SQL-forespørgsel:


CREATE TABLE IF NOT EXISTS `mysocialnetwork`.`Pictures` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Filename` VARCHAR(128) NOT NULL,
  `Title` VARCHAR(45) NULL,
  `PictureDesc` TEXT NULL,
  `Owner` INT NOT NULL,
  `DateAdded` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  INDEX `fk_Pictures_Users1_idx` (`Owner` ASC),
  CONSTRAINT `fk_Pictures_Users1`
    FOREIGN KEY (`Owner`)
    REFERENCES `mysocialnetwork`.`Users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
MySQL returnerede: Dokumentation

#1215 - Cannot add foreign key constraint
Åbn nyt phpMyAdmin vindue
```

**Comment by dkhansemand** [comment]
SQL opdateret, prøv at importere den igen.
"Mulig" Fejl (40):
Pictures oprettes før users og prøver at skabe en relation til Pictures.Owner --> users.Id
Men ikke muligt da users tabellen ikke op oprettet.

**Comment by Bedja** [comment]
Fejl
SQL-forespørgsel:


INSERT INTO `mysocialnetwork`.`Pictures` (`Id`, `Filename`, `Title`, `PictureDesc`, `Owner`, `DateAdded`) VALUES (1, 'avatar.jpg', 'Default Profile picture', 'Profile picture', 1, DEFAULT)
MySQL returnerede: Dokumentation

#1452 - Cannot add or update a child row: a foreign key constraint fails (`mysocialnetwork`.`pictures`, CONSTRAINT `fk_Pictures_Users1` FOREIGN KEY (`Owner`) REFERENCES `Users` (`Id`) ON DELETE NO ACTION ON UPDATE NO ACTION)

**Comment by Bedja** [comment]
Fejl
SQL-forespørgsel:


INSERT INTO `mysocialnetwork`.`Users` (`Id`, `Username`, `Email`, `Password`) VALUES (1, 'System', 'admin@system.dk', '1234root')
MySQL returnerede: Dokumentation

#1452 - Cannot add or update a child row: a foreign key constraint fails (`mysocialnetwork`.`userdetails`, CONSTRAINT `fk_ProfilePicture` FOREIGN KEY (`ProfilePictureId`) REFERENCES `Pictures` (`Id`) ON DELETE CASCADE ON UPDATE NO ACTION)

**Comment by dkhansemand** [comment]
Sql opdateret, melder ingen fejl via workbench - Issue resolved

**Comment by Bedja** [comment]
<img width="364" alt="skaermbillede 2017-02-08 kl 12 54 20" src="https://cloud.githubusercontent.com/assets/20585696/22736303/c167786c-edfd-11e6-8b18-63ea966cb2ed.png">

Modtager denne fejl hvis jeg forsøger at edit en burger direkte i mysql.

**Comment by dkhansemand** [comment]
Post lige hele forespørgelsen her

**Comment by Bedja** [comment]
Det er hele forsørgelsen hvis jeg forsøger at rette en bruger direkte i PhpMyadmin modtager jeg denne

**Comment by dkhansemand** [comment]
PhpMyAdmin fejl evt. ? Hvorfor er der en WHERE på uden at definere noget konkret virker lidt mytisk

**Comment by Bedja** [comment]
Lad den ligge vi må lige se om der kommer nogen problemer i forhold til Slet bruger

**Comment by Madsen2880** [comment]
:-)Fejl
SQL-forespørgsel:


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
MySQL returnerede: Dokumentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS' at line 3

**Comment by Bedja** [comment]
Han køre dog version 5.4 så nok den der driller

**Comment by dkhansemand** [comment]
Ja sikkert det som er problemet, jeg køre på 5.6.24
@Madsen2880 prøv at fjerne de linjer fra sql filen og lave en frisk import efter du har slettet DB'en (hvis den har oprettet den)  ca. fra linje 136 i sql2.sql:
DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

**Comment by Bedja** [comment]
Har lige testet ved at slette de linjer men genere stadig fejl. og har lige tjekket hans MySql Version og den fungere fint samme version som dig 

ny fejl returnere en #1064 på linje 4

**Comment by Madsen2880** [comment]
Fejl
SQL-forespørgsel:


CREATE DEFINER = CURRENT_USER TRIGGER `mysocialnetwork`.`Users_AFTER_INSERT` AFTER INSERT ON `Users` FOR EACH ROW
BEGIN
	INSERT INTO `mysocialnetwork`.`Userdetails` (ProfilePictureId, UserId)VALUES(1, NEW.Id);
END$$


MySQL returnerede: Dokumentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4

**Comment by Madsen2880** [comment]
Server: 127.0.0.1 via TCP/IP
Servertype: MySQL
Serverversion: 5.6.24 - MySQL Community Server (GPL)
Protokolversion: 10
Bruger: root@localhost
Servers tegnsæt: UTF-8 Unicode (utf8)
Webserver

Apache/2.4.12 (Win32) OpenSSL/1.0.1l PHP/5.6.8
Databaseklientversion: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $
PHP-udvidelse: mysqli Dokumentation
phpMyAdmin

Versionsinformation: 4.3.11, seneste stabile version: 4.6.6

**Comment by dkhansemand** [comment]
SQL fil opdateret, testet via PhpMyAdmin og melder ingen fejl nu. husk at DROP database mysocialnetwork :-)

**Comment by Madsen2880** [comment]
Ser ud til at virke nu.. :-)
