### ISSUE TITLE
mangler ny DB :D

### ISSUE THREAD

**Issue by Bedja** [dkhansemand/MySocialNetwork#4]
kan ikke engang login lige nu 🐤

**Comment by dkhansemand** [comment]
Poster lige en export af DB her om snart

**Comment by dkhansemand** [comment]
mysocialnetwork.sql i Database er nu et udtræk direkte fra phpMyAdmin. Test om alt virker tak 🗡

**Comment by Bedja** [comment]
har lige forsøgt at load det hele op uden held db kommer fint igennem men kan ikke logge ind. samt kan bliver ikke længere ført til create user. mv... kan se brugeren fint bliver oprettet.
